// apps/web-admin/src/App.vue
<script setup lang="ts">
import { useConvexQuery, useConvexMutation } from 'convex-vue'
import { api } from '../../../convex/_generated/api'
import type { Id } from '../../../convex/_generated/dataModel'

const { data: todos, isPending } = useConvexQuery(api.todos.getTodos)
const { mutate: deleteTodo } = useConvexMutation(api.todos.deleteTodo)
const { mutate: updateTodo } = useConvexMutation(api.todos.updateTodo)

// Delete todo
const handleDelete = async (id: Id<'todos'>) => {
  if (confirm('Are you sure you want to delete this todo?')) {
    await deleteTodo({ id })
  }
}

// Toggle completion
const handleToggleComplete = async (todo: { _id: Id<'todos'>, text: string, completed: boolean }) => {
  await updateTodo({
    id: todo._id,
    text: todo.text,
    completed: !todo.completed
  })
}
</script>

<template>
  <div class="app">
    <div class="container">
      <header class="header">
        <h1>Admin Dashboard</h1>
        <p class="subtitle">Manage all todos</p>
      </header>

      <!-- Stats -->
      <div v-if="!isPending && todos" class="stats">
        <div class="stat-card">
          <div class="stat-value">{{ todos.length }}</div>
          <div class="stat-label">Total Todos</div>
        </div>
        <div class="stat-card">
          <div class="stat-value">{{ todos.filter(t => t.completed).length }}</div>
          <div class="stat-label">Completed</div>
        </div>
        <div class="stat-card">
          <div class="stat-value">{{ todos.filter(t => !t.completed).length }}</div>
          <div class="stat-label">Pending</div>
        </div>
      </div>

      <!-- Loading State -->
      <div v-if="isPending" class="loading">Loading todos...</div>

      <!-- Todos Table -->
      <div v-else-if="todos && todos.length > 0" class="todos-table">
        <table>
          <thead>
            <tr>
              <th>Status</th>
              <th>Text</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <tr
              v-for="todo in todos"
              :key="todo._id"
              :class="{ completed: todo.completed }"
            >
              <td>
                <input
                  type="checkbox"
                  :checked="todo.completed"
                  @change="handleToggleComplete(todo)"
                  class="todo-checkbox"
                />
              </td>
              <td>
                <span :class="{ 'text-completed': todo.completed }">
                  {{ todo.text }}
                </span>
              </td>
              <td>
                <button
                  @click="handleDelete(todo._id)"
                  class="btn btn-delete"
                >
                  Delete
                </button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <!-- Empty State -->
      <div v-else class="empty-state">
        <p>No todos found.</p>
      </div>
    </div>
  </div>
</template>

<style scoped>
.app {
  min-height: 100vh;
  background: linear-gradient(135deg, #1e3c72 0%, #2a5298 100%);
  padding: 2rem;
}

.container {
  max-width: 1200px;
  margin: 0 auto;
  background: white;
  border-radius: 12px;
  padding: 2rem;
  box-shadow: 0 10px 40px rgba(0, 0, 0, 0.2);
}

.header {
  text-align: center;
  margin-bottom: 2rem;
  padding-bottom: 1rem;
  border-bottom: 2px solid #e0e0e0;
}

h1 {
  color: #1e3c72;
  margin-bottom: 0.5rem;
  font-size: 2rem;
}

.subtitle {
  color: #666;
  font-size: 1.1rem;
}

.stats {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap: 1.5rem;
  margin-bottom: 2rem;
}

.stat-card {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
  padding: 1.5rem;
  border-radius: 8px;
  text-align: center;
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
}

.stat-value {
  font-size: 2.5rem;
  font-weight: bold;
  margin-bottom: 0.5rem;
}

.stat-label {
  font-size: 0.9rem;
  opacity: 0.9;
}

.loading {
  text-align: center;
  padding: 3rem;
  color: #666;
  font-size: 1.1rem;
}

.todos-table {
  overflow-x: auto;
}

table {
  width: 100%;
  border-collapse: collapse;
}

thead {
  background: #f5f5f5;
}

th {
  padding: 1rem;
  text-align: left;
  font-weight: 600;
  color: #333;
  border-bottom: 2px solid #e0e0e0;
}

td {
  padding: 1rem;
  border-bottom: 1px solid #e0e0e0;
}

tr:hover {
  background: #f9f9f9;
}

tr.completed {
  background: #f5f5f5;
  opacity: 0.7;
}

.todo-checkbox {
  width: 20px;
  height: 20px;
  cursor: pointer;
}

.text-completed {
  text-decoration: line-through;
  color: #999;
}

.btn {
  padding: 0.5rem 1rem;
  border: none;
  border-radius: 6px;
  font-size: 0.9rem;
  cursor: pointer;
  transition: all 0.2s;
  font-weight: 500;
}

.btn-delete {
  background: #f44336;
  color: white;
}

.btn-delete:hover {
  background: #d32f2f;
}

.empty-state {
  text-align: center;
  padding: 3rem;
  color: #999;
  font-size: 1.1rem;
}

@media (max-width: 768px) {
  .app {
    padding: 1rem;
  }

  .container {
    padding: 1.5rem;
  }

  .stats {
    grid-template-columns: 1fr;
  }

  table {
    font-size: 0.9rem;
  }

  th,
  td {
    padding: 0.75rem 0.5rem;
  }
}
</style>

// apps/mobile-admin/App.tsx
import { StatusBar } from 'expo-status-bar';
import {
  StyleSheet,
  Text,
  View,
  FlatList,
  Alert,
  TouchableOpacity,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ConvexProvider, useQuery, useMutation, ConvexReactClient } from 'convex/react';
import { api } from '../../convex/_generated/api';
import type { Id } from '../../convex/_generated/dataModel';

const convex = new ConvexReactClient(process.env.EXPO_PUBLIC_CONVEX_URL || '');

function AdminDashboard() {
  const todos = useQuery(api.todos.getTodos);
  const updateTodo = useMutation(api.todos.updateTodo);
  const deleteTodo = useMutation(api.todos.deleteTodo);

  const handleToggleComplete = async (todo: { _id: Id<'todos'>, text: string, completed: boolean }) => {
    try {
      await updateTodo({
        id: todo._id,
        text: todo.text,
        completed: !todo.completed,
      });
    } catch (error) {
      Alert.alert('Error', 'Failed to update todo');
    }
  };

  const handleDelete = async (id: Id<'todos'>) => {
    Alert.alert(
      'Delete Todo',
      'Are you sure you want to delete this todo?',
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Delete',
          style: 'destructive',
          onPress: async () => {
            try {
              await deleteTodo({ id });
            } catch (error) {
              Alert.alert('Error', 'Failed to delete todo');
            }
          },
        },
      ]
    );
  };

  if (todos === undefined) {
    return (
      <View style={styles.centerContainer}>
        <Text style={styles.loadingText}>Loading todos...</Text>
      </View>
    );
  }

  const completedCount = todos.filter(t => t.completed).length;
  const pendingCount = todos.filter(t => !t.completed).length;

  const ListHeader = () => (
    <View style={styles.headerContainer}>
      <Text style={styles.title}>Admin Mobile Dashboard</Text>
      <Text style={styles.subtitle}>Manage all todos</Text>

      {/* Stats */}
      <View style={styles.statsContainer}>
        <View style={styles.statCard}>
          <Text style={styles.statValue}>{todos.length}</Text>
          <Text style={styles.statLabel}>Total</Text>
        </View>
        <View style={styles.statCard}>
          <Text style={styles.statValue}>{completedCount}</Text>
          <Text style={styles.statLabel}>Completed</Text>
        </View>
        <View style={styles.statCard}>
          <Text style={styles.statValue}>{pendingCount}</Text>
          <Text style={styles.statLabel}>Pending</Text>
        </View>
      </View>
    </View>
  );

  const ListEmpty = () => (
    <View style={styles.centerContainer}>
      <Text style={styles.emptyText}>No todos found.</Text>
    </View>
  );

  return (
    <SafeAreaView style={styles.container} edges={['top', 'bottom']}>
      <FlatList
        data={todos}
        keyExtractor={(item) => item._id}
        ListHeaderComponent={ListHeader}
        ListEmptyComponent={ListEmpty}
        contentContainerStyle={todos.length === 0 ? styles.emptyListContainer : styles.listContainer}
        renderItem={({ item }) => (
              <View style={[styles.todoItem, item.completed && styles.todoCompleted]}>
                <View style={styles.todoContent}>
                  <TouchableOpacity
                    style={styles.checkbox}
                    onPress={() => handleToggleComplete(item)}
                  >
                    <Text style={styles.checkboxText}>
                      {item.completed ? '☑' : '☐'}
                    </Text>
                  </TouchableOpacity>
                  <Text
                    style={[
                      styles.todoText,
                      item.completed && styles.todoTextCompleted,
                    ]}
                  >
                    {item.text}
                  </Text>
                  <TouchableOpacity
                    style={[styles.button, styles.deleteButton]}
                    onPress={() => handleDelete(item._id)}
                  >
                    <Text style={styles.buttonText}>Delete</Text>
                  </TouchableOpacity>
                </View>
              </View>
            )}
      />
      <StatusBar style="auto" />
    </SafeAreaView>
  );
}

export default function App() {
  return (
    <ConvexProvider client={convex}>
      <AdminDashboard />
    </ConvexProvider>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  headerContainer: {
    padding: 16,
    paddingBottom: 8,
  },
  listContainer: {
    padding: 16,
    paddingTop: 8,
  },
  emptyListContainer: {
    flex: 1,
    padding: 16,
  },
  centerContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#1e3c72',
    textAlign: 'center',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
    marginBottom: 24,
  },
  statsContainer: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 20,
  },
  statCard: {
    flex: 1,
    backgroundColor: '#1e3c72',
    padding: 16,
    borderRadius: 8,
    alignItems: 'center',
  },
  statValue: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 12,
    color: '#fff',
    opacity: 0.9,
  },
  todoItem: {
    backgroundColor: '#fff',
    padding: 16,
    borderRadius: 8,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  todoCompleted: {
    opacity: 0.7,
    backgroundColor: '#f9f9f9',
  },
  todoContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  checkbox: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxText: {
    fontSize: 20,
  },
  todoText: {
    flex: 1,
    fontSize: 16,
    color: '#333',
  },
  todoTextCompleted: {
    textDecorationLine: 'line-through',
    color: '#999',
  },
  button: {
    padding: 8,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteButton: {
    backgroundColor: '#f44336',
    paddingHorizontal: 12,
  },
  buttonText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 12,
  },
  loadingText: {
    fontSize: 16,
    color: '#666',
  },
  emptyText: {
    fontSize: 16,
    color: '#999',
    textAlign: 'center',
  },
});
