// apps/mobile-customer/App.tsx
import { StatusBar } from 'expo-status-bar';
import { useState } from 'react';
import {
  StyleSheet,
  Text,
  View,
  TextInput,
  TouchableOpacity,
  FlatList,
  Alert,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ConvexProvider, useQuery, useMutation, ConvexReactClient } from 'convex/react';
import { api } from '../../convex/_generated/api';
import type { Id } from '../../convex/_generated/dataModel';

const convex = new ConvexReactClient(process.env.EXPO_PUBLIC_CONVEX_URL || '');

function TodoList() {
  const todos = useQuery(api.todos.getTodos);
  const addTodo = useMutation(api.todos.addTodo);
  const updateTodo = useMutation(api.todos.updateTodo);
  const deleteTodo = useMutation(api.todos.deleteTodo);

  const [newTodoText, setNewTodoText] = useState('');
  const [editingId, setEditingId] = useState<Id<'todos'> | null>(null);
  const [editingText, setEditingText] = useState('');

  const handleAddTodo = async () => {
    if (!newTodoText.trim()) return;
    try {
      await addTodo({ text: newTodoText.trim() });
      setNewTodoText('');
    } catch (error) {
      Alert.alert('Error', 'Failed to add todo');
    }
  };

  const handleToggleComplete = async (todo: { _id: Id<'todos'>, text: string, completed: boolean }) => {
    try {
      await updateTodo({
        id: todo._id,
        text: todo.text,
        completed: !todo.completed,
      });
    } catch (error) {
      Alert.alert('Error', 'Failed to update todo');
    }
  };

  const handleDelete = async (id: Id<'todos'>) => {
    Alert.alert(
      'Delete Todo',
      'Are you sure you want to delete this todo?',
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Delete',
          style: 'destructive',
          onPress: async () => {
            try {
              await deleteTodo({ id });
            } catch (error) {
              Alert.alert('Error', 'Failed to delete todo');
            }
          },
        },
      ]
    );
  };

  const startEdit = (todo: { _id: Id<'todos'>, text: string, completed: boolean }) => {
    setEditingId(todo._id);
    setEditingText(todo.text);
  };

  const handleSaveEdit = async (id: Id<'todos'>, completed: boolean) => {
    if (!editingText.trim()) {
      setEditingId(null);
      return;
    }
    try {
      await updateTodo({
        id,
        text: editingText.trim(),
        completed,
      });
      setEditingId(null);
      setEditingText('');
    } catch (error) {
      Alert.alert('Error', 'Failed to update todo');
    }
  };

  if (todos === undefined) {
    return (
      <View style={styles.centerContainer}>
        <Text style={styles.loadingText}>Loading todos...</Text>
      </View>
    );
  }

  const ListHeader = () => (
    <View style={styles.headerContainer}>
      <Text style={styles.title}>Customer Mobile App</Text>
      <Text style={styles.subtitle}>Todo Manager</Text>

      {/* Add Todo Form */}
      <View style={styles.addForm}>
        <TextInput
          style={styles.input}
          placeholder="Add a new todo..."
          value={newTodoText}
          onChangeText={setNewTodoText}
          onSubmitEditing={handleAddTodo}
        />
        <TouchableOpacity
          style={[styles.button, styles.addButton]}
          onPress={handleAddTodo}
          disabled={!newTodoText.trim()}
        >
          <Text style={styles.buttonText}>Add</Text>
        </TouchableOpacity>
      </View>
    </View>
  );

  const ListEmpty = () => (
    <View style={styles.centerContainer}>
      <Text style={styles.emptyText}>No todos yet. Add one above!</Text>
    </View>
  );

  return (
    <SafeAreaView style={styles.container} edges={['top', 'bottom']}>
      <FlatList
        data={todos}
        keyExtractor={(item) => item._id}
        ListHeaderComponent={ListHeader}
        ListEmptyComponent={ListEmpty}
        contentContainerStyle={todos.length === 0 ? styles.emptyListContainer : styles.listContainer}
        renderItem={({ item }) => (
              <View style={[styles.todoItem, item.completed && styles.todoCompleted]}>
                {editingId === item._id ? (
                  <View style={styles.editContainer}>
                    <TextInput
                      style={styles.editInput}
                      value={editingText}
                      onChangeText={setEditingText}
                      autoFocus
                    />
                    <TouchableOpacity
                      style={[styles.button, styles.saveButton]}
                      onPress={() => handleSaveEdit(item._id, item.completed)}
                    >
                      <Text style={styles.buttonText}>Save</Text>
                    </TouchableOpacity>
                    <TouchableOpacity
                      style={[styles.button, styles.cancelButton]}
                      onPress={() => {
                        setEditingId(null);
                        setEditingText('');
                      }}
                    >
                      <Text style={styles.buttonText}>Cancel</Text>
                    </TouchableOpacity>
                  </View>
                ) : (
                  <View style={styles.todoContent}>
                    <TouchableOpacity
                      style={styles.checkbox}
                      onPress={() => handleToggleComplete(item)}
                    >
                      <Text style={styles.checkboxText}>
                        {item.completed ? '☑' : '☐'}
                      </Text>
                    </TouchableOpacity>
                    <Text
                      style={[
                        styles.todoText,
                        item.completed && styles.todoTextCompleted,
                      ]}
                    >
                      {item.text}
                    </Text>
                    <View style={styles.todoActions}>
                      <TouchableOpacity
                        style={[styles.button, styles.editButton]}
                        onPress={() => startEdit(item)}
                      >
                        <Text style={styles.buttonText}>✏️</Text>
                      </TouchableOpacity>
                      <TouchableOpacity
                        style={[styles.button, styles.deleteButton]}
                        onPress={() => handleDelete(item._id)}
                      >
                        <Text style={styles.buttonText}>🗑️</Text>
                      </TouchableOpacity>
                    </View>
                  </View>
                )}
              </View>
            )}
      />
      <StatusBar style="auto" />
    </SafeAreaView>
  );
}

export default function App() {
  return (
    <ConvexProvider client={convex}>
      <TodoList />
    </ConvexProvider>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  headerContainer: {
    padding: 16,
    paddingBottom: 8,
  },
  listContainer: {
    padding: 16,
    paddingTop: 8,
  },
  emptyListContainer: {
    flex: 1,
    padding: 16,
  },
  centerContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#42b983',
    textAlign: 'center',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
    marginBottom: 24,
  },
  addForm: {
    flexDirection: 'row',
    marginBottom: 20,
    gap: 8,
  },
  input: {
    flex: 1,
    backgroundColor: '#fff',
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e0e0e0',
    fontSize: 16,
  },
  button: {
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 60,
  },
  addButton: {
    backgroundColor: '#42b983',
  },
  saveButton: {
    backgroundColor: '#2196f3',
  },
  cancelButton: {
    backgroundColor: '#757575',
  },
  editButton: {
    backgroundColor: '#2196f3',
    padding: 8,
    minWidth: 40,
  },
  deleteButton: {
    backgroundColor: '#f44336',
    padding: 8,
    minWidth: 40,
  },
  buttonText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 14,
  },
  todoItem: {
    backgroundColor: '#fff',
    padding: 16,
    borderRadius: 8,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  todoCompleted: {
    opacity: 0.7,
    backgroundColor: '#f9f9f9',
  },
  todoContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  checkbox: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxText: {
    fontSize: 20,
  },
  todoText: {
    flex: 1,
    fontSize: 16,
    color: '#333',
  },
  todoTextCompleted: {
    textDecorationLine: 'line-through',
    color: '#999',
  },
  todoActions: {
    flexDirection: 'row',
    gap: 8,
  },
  editContainer: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  editInput: {
    flex: 1,
    backgroundColor: '#f5f5f5',
    padding: 10,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#e0e0e0',
    fontSize: 16,
  },
  loadingText: {
    fontSize: 16,
    color: '#666',
  },
  emptyText: {
    fontSize: 16,
    color: '#999',
    textAlign: 'center',
  },
});

// apps/web-customer/src/App.vue
<script setup lang="ts">
import { ref, nextTick } from 'vue'
import { useConvexQuery, useConvexMutation } from 'convex-vue'
import { api } from '../../../convex/_generated/api'
import type { Id } from '../../../convex/_generated/dataModel'

const { data: todos, isPending } = useConvexQuery(api.todos.getTodos)
const { mutate: addTodo, isPending: isAdding } = useConvexMutation(api.todos.addTodo)
const { mutate: updateTodo } = useConvexMutation(api.todos.updateTodo)
const { mutate: deleteTodo } = useConvexMutation(api.todos.deleteTodo)

// Form state
const newTodoText = ref('')
const editingId = ref<Id<'todos'> | null>(null)
const editingText = ref('')

// Add new todo
const handleAddTodo = async () => {
  if (!newTodoText.value.trim()) return
  await addTodo({ text: newTodoText.value.trim() })
  newTodoText.value = ''
}

// Toggle todo completion
const handleToggleComplete = async (todo: { _id: Id<'todos'>, text: string, completed: boolean }) => {
  await updateTodo({
    id: todo._id,
    text: todo.text,
    completed: !todo.completed
  })
}

// Start editing
const startEdit = (todo: { _id: Id<'todos'>, text: string, completed: boolean }) => {
  editingId.value = todo._id
  editingText.value = todo.text
}

// Cancel editing
const cancelEdit = () => {
  editingId.value = null
  editingText.value = ''
}

// Save edited todo
const handleSaveEdit = async (id: Id<'todos'>, completed: boolean) => {
  if (!editingText.value.trim()) {
    cancelEdit()
    return
  }
  await updateTodo({
    id,
    text: editingText.value.trim(),
    completed
  })
  cancelEdit()
}

// Delete todo
const handleDelete = async (id: Id<'todos'>) => {
  if (confirm('Are you sure you want to delete this todo?')) {
    await deleteTodo({ id })
  }
}
</script>

<template>
  <div class="app">
    <div class="container">
      <h1>Customer Web App - Todo Manager</h1>
      <p class="subtitle">Convex backend is connected!</p>

      <!-- Add Todo Form -->
      <div class="add-todo-form">
        <input
          v-model="newTodoText"
          type="text"
          placeholder="Add a new todo..."
          class="todo-input"
          @keyup.enter="handleAddTodo"
        />
        <button
          @click="handleAddTodo"
          :disabled="isAdding || !newTodoText.trim()"
          class="btn btn-primary"
        >
          {{ isAdding ? 'Adding...' : 'Add Todo' }}
        </button>
      </div>

      <!-- Loading State -->
      <div v-if="isPending" class="loading">Loading todos...</div>

      <!-- Todos List -->
      <template v-else-if="todos && todos.length > 0">
        <div class="todos-list">
          <div
            v-for="todo in todos"
            :key="todo._id"
            class="todo-item"
            :class="{ completed: todo.completed }"
          >
          <!-- Edit Mode -->
          <div v-if="editingId === todo._id" class="todo-edit">
            <input
              v-model="editingText"
              type="text"
              class="todo-input"
              @keyup.enter="handleSaveEdit(todo._id, todo.completed)"
              @keyup.esc="cancelEdit"
            />
            <button
              @click="handleSaveEdit(todo._id, todo.completed)"
              class="btn btn-save"
            >
              Save
            </button>
            <button
              @click="cancelEdit"
              class="btn btn-cancel"
            >
              Cancel
            </button>
          </div>

          <!-- View Mode -->
          <div v-else class="todo-view">
            <input
              type="checkbox"
              :checked="todo.completed"
              @change="handleToggleComplete(todo)"
              class="todo-checkbox"
            />
            <span
              class="todo-text"
              :class="{ 'text-completed': todo.completed }"
            >
              {{ todo.text }}
            </span>
            <div class="todo-actions">
              <button
                @click="startEdit(todo)"
                class="btn btn-edit"
                title="Edit"
              >
                ✏️
              </button>
              <button
                @click="handleDelete(todo._id)"
                class="btn btn-delete"
                title="Delete"
              >
                🗑️
              </button>
            </div>
          </div>
        </div>
        </div>
      </template>

      <!-- Empty State -->
      <div v-else class="empty-state">
        <p>No todos yet. Add one above to get started!</p>
      </div>
    </div>
  </div>
</template>

<style scoped>
.app {
  min-height: 100vh;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  padding: 2rem;
}

.container {
  max-width: 600px;
  margin: 0 auto;
  background: white;
  border-radius: 12px;
  padding: 2rem;
  box-shadow: 0 10px 40px rgba(0, 0, 0, 0.1);
}

h1 {
  color: #42b983;
  margin-bottom: 0.5rem;
  text-align: center;
}

.subtitle {
  text-align: center;
  color: #666;
  margin-bottom: 2rem;
}

.add-todo-form {
  display: flex;
  gap: 0.5rem;
  margin-bottom: 2rem;
}

.todo-input {
  flex: 1;
  padding: 0.75rem;
  border: 2px solid #e0e0e0;
  border-radius: 6px;
  font-size: 1rem;
  transition: border-color 0.2s;
}

.todo-input:focus {
  outline: none;
  border-color: #42b983;
}

.btn {
  padding: 0.75rem 1.5rem;
  border: none;
  border-radius: 6px;
  font-size: 1rem;
  cursor: pointer;
  transition: all 0.2s;
  font-weight: 500;
}

.btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.btn-primary {
  background: #42b983;
  color: white;
}

.btn-primary:hover:not(:disabled) {
  background: #35a372;
}

.btn-edit,
.btn-save {
  background: #2196f3;
  color: white;
  padding: 0.5rem 1rem;
  font-size: 0.9rem;
}

.btn-edit:hover,
.btn-save:hover {
  background: #1976d2;
}

.btn-delete {
  background: #f44336;
  color: white;
  padding: 0.5rem 1rem;
  font-size: 0.9rem;
}

.btn-delete:hover {
  background: #d32f2f;
}

.btn-cancel {
  background: #757575;
  color: white;
  padding: 0.5rem 1rem;
  font-size: 0.9rem;
}

.btn-cancel:hover {
  background: #616161;
}

.loading {
  text-align: center;
  padding: 2rem;
  color: #666;
}

.todos-list {
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
}

.todo-item {
  padding: 1rem;
  border: 2px solid #e0e0e0;
  border-radius: 8px;
  transition: all 0.2s;
}

.todo-item:hover {
  border-color: #42b983;
  box-shadow: 0 2px 8px rgba(66, 185, 131, 0.1);
}

.todo-item.completed {
  background: #f5f5f5;
  opacity: 0.8;
}

.todo-view {
  display: flex;
  align-items: center;
  gap: 1rem;
}

.todo-checkbox {
  width: 20px;
  height: 20px;
  cursor: pointer;
}

.todo-text {
  flex: 1;
  font-size: 1rem;
  word-break: break-word;
}

.text-completed {
  text-decoration: line-through;
  color: #999;
}

.todo-actions {
  display: flex;
  gap: 0.5rem;
}

.todo-edit {
  display: flex;
  gap: 0.5rem;
  align-items: center;
}

.todo-edit .todo-input {
  flex: 1;
}

.empty-state {
  text-align: center;
  padding: 3rem 1rem;
  color: #999;
}

.empty-state p {
  font-size: 1.1rem;
}

@media (max-width: 640px) {
  .app {
    padding: 1rem;
  }

  .container {
    padding: 1.5rem;
  }

  .add-todo-form {
    flex-direction: column;
  }

  .todo-view {
    flex-wrap: wrap;
  }

  .todo-actions {
    width: 100%;
    justify-content: flex-end;
  }
}
</style>
